### ISSUE TITLE
name & not working

### ISSUE THREAD

**Issue by zacheryph** [fisherman/masenko#1]
`fisher masenko` does not work as masenko is not the name. `fisher roach` does work.

error: `set_color: Unknown color ' ~ '`

**Comment by bucaran** [comment]
`masenko` does not exist anymore and `roach` is still work in progress. I hope to finish this theme when I am done with a few other plugins in my todo pipeline.

**Comment by bucaran** [comment]
@zacheryph Finally, it's fixed. Sorry for taking forever.

**Comment by bucaran** [comment]
<img width="1280" alt="screen shot 2016-05-10 at 11 00 44 pm" src="https://cloud.githubusercontent.com/assets/8317250/15149065/0eeb77f0-1703-11e6-9a5b-70713390667e.png">

**Comment by zacheryph** [comment]
No apology necessary.  Looks amazing :)
